# -*- coding: utf-8 -*-
"""final29.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwWiQtCPm9MaAn35TL6oxzhx_bWqDbzB
"""

print("นี่คือโปรแกรมคำนวณอายุตามปีเกิดค่ะ")
years = int(input("\nกรุณากรอกปีเกิดค่ะ (พ.ศ.) : "))

age = (2569 - years)

print("\nอายุของคุณคือ",age,"ปี")

print("\nCreate by Punyanuch (N'Aoey)")